site_name: Experiences, Goals and Aspiration
theme:
    name: material
    palette:
        primary: white
    favicon: static/logo.png
    logo: static/logo.png

nav:
    - index.md
    - AboutMe.md
    - WhyLeave.md
    - WhatDoIDo.md
    - ProudOf.md
    - Strengths.md
    - MentorJunior.md
    - OnBoarding.md
    - DifficultDecision.md
    - WorkedWellTeam.md
    - MatterToUser.md
    - DoneDifferently.md
    - DificultFeedback.md
    - FavLanguage.md
    - Closing.md
    - Questions.md
    - Smalltalk.md
    - Conflict.md
    - Criticism.md 
    - Disagreed.md
    - NextRole.md
    - Ownership.md
    - Todo.md
    - Unfair.md
    - Weakness.md
    - Template.md



    




  
