site_name: Experiences, Goals and Aspiration
theme:
    name: material
    palette:
        primary: white
    favicon: static/logo.png
    logo: static/logo.png

nav:
    - index.md
    - AboutMe.md
    - WhyLeave.md
    - WhatDoIDo.md
    - Ownership.md
    - Strengths.md
    - MentorJunior.md
    - OnBoarding.md
    - DifficultDecision.md
    - WorkedWellTeam.md
    - MatterToUser.md
    - DificultFeedback.md
    - FavLanguage.md